
variables:

  ### Disable cache in Docker builds, as this has occasionally resulted in images not containing what was
  ### expected multiple MRs where being built/retried.
  NO_CACHE: 'true'
  ### Replace RESOURCE with the name of the image you want to build and publish in OpenShift
  ### Important! In order for this template to work, the name of the gitlab repo must match
  ### also the variable name
  RESOURCE: cern-search-rest-api
  ###
  ### You shouldn't change the following variables
  NAMESPACE: openshift
  OPENSHIFT_SERVER: https://openshift-dev.cern.ch


### By default, there are 6 stages that we may use:
### Feel free to adapt this to your specific case.
stages:
  - build
  - tag_image
  - import_image # This stage is only used when the built image is stored in the GitLab Registry
  - deploy

### 'Build' stage
### Build the image and store it in the registry. It is important that this step
### doesn't override the image the applications are running, as we haven't tested the image yet

build_dev_version:
  stage: build
  except:
    - tags
    - master
  environment: dev
  tags:
    - docker-image-build
  script: 'echo "Building Dev/QA Docker image..."'

### When building tags, use the git tag as the docker tag of the image
build_tagged_version:
  stage: build
  only:
    - tags
  tags:
    - docker-image-build
  script: 'echo "Building Docker image..."'
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}

### If a new tag is pushed it needs to be referenced into the ImageStream
tag_image_dev: &tag_image
  stage: tag_image
  only:
  - tags
  environment: staging
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  script:
    - oc tag --source=docker ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${RESOURCE}:${CI_COMMIT_TAG} --token=${TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE}
  variables:
    TOKEN: ${SERVICE_ACCOUNT_TOKEN_DEV}

### Import image into OpenShift. Import $CI_COMMIT_TAG if present or 'latest' if not.
import_image_dev:
  stage: import_image
  environment: staging
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  script:
    - oc import-image ${RESOURCE}:${CI_COMMIT_TAG:-latest} --token=${TOKEN} --server=${OPENSHIFT_SERVER} -n ${NAMESPACE}
  variables:
    TOKEN: ${SERVICE_ACCOUNT_TOKEN_DEV}